### ISSUE TITLE
mch does not work

### ISSUE THREAD

**Issue by a-happin** [mcenv/mch#41]
I tried mch for the first time but it does not work.
I assume this is a bug in mch. Or did I do something wrong?

#### Environment
- java: openjdk 17.0.6
- Minecraft: 1.19.4
- mch: v0.8.0

#### mch.properties
```
#Wed Apr 05 14:31:48 UTC 2023
forks=5
warmup-iterations=5
parsing-benchmarks=,
execute-benchmarks=a,b
mc-args=nogui
time=10
time-unit=s
jvm-args=,
measurement-iterations=5
```

#### This is a part of the log.
```
Starting mch.main.Main
Installing datapack in world/datapacks/mch.zip
Starting mch.agent.Agent
Starting mch.fork.Fork
Starting net.minecraft.server.Main
[14:31:53] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:31:55] [ServerMain/INFO]: Loaded 7 recipes
[14:31:55] [ServerMain/INFO]: Loaded 1179 advancements
[14:31:55] [Server thread/INFO]: Starting minecraft server version 1.19.4
[14:31:55] [Server thread/INFO]: Loading properties
[14:31:55] [Server thread/INFO]: Default game type: SURVIVAL
[14:31:55] [Server thread/INFO]: Generating keypair
[14:31:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:31:56] [Server thread/INFO]: Using epoll channel type
[14:31:56] [Server thread/INFO]: Preparing level "world"
[14:31:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:31:59] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:00] [Worker-Main-1/INFO]: Preparing spawn area: 90%
[14:32:00] [Server thread/INFO]: Time elapsed: 4175 ms
[14:32:00] [Server thread/INFO]: Done (4.310s)! For help, type "help"
[14:32:00] [Server thread/INFO]: Starting remote control listener
[14:32:00] [Server thread/INFO]: Thread RCON Listener started
[14:32:00] [Server thread/INFO]: RCON running on 0.0.0.0:25575
[14:32:00] [Server thread/INFO]: Stopping server
[14:32:00] [Server thread/INFO]: Saving players
[14:32:00] [Server thread/INFO]: Saving worlds
[14:32:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:32:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[14:32:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[14:32:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:32:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:32:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:32:04] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:32:04] [Server thread/INFO]: Thread RCON Listener stopped
Starting mch.agent.Agent
Starting mch.fork.Fork
Starting net.minecraft.server.Main
[14:32:09] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:32:10] [ServerMain/INFO]: Loaded 7 recipes
[14:32:10] [ServerMain/ERROR]: Failed to load function mch:loop
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at dm.a(SourceFile:63) ~[server-1.19.4.jar:?]
	at adq.a(SourceFile:83) ~[server-1.19.4.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[14:32:10] [ServerMain/ERROR]: Failed to load function mch:post
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at dm.a(SourceFile:63) ~[server-1.19.4.jar:?]
	at adq.a(SourceFile:83) ~[server-1.19.4.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[14:32:10] [ServerMain/ERROR]: Failed to load function mch:start
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown or incomplete command, see below for error at position 0: <--[HERE]
	at dm.a(SourceFile:63) ~[server-1.19.4.jar:?]
	at adq.a(SourceFile:83) ~[server-1.19.4.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[14:32:10] [ServerMain/ERROR]: Couldn't load tag minecraft:load as it is missing following references: mch:start (from file/mch.zip), mch:post (from file/mch.zip)
[14:32:10] [ServerMain/INFO]: Loaded 1179 advancements
[14:32:11] [Server thread/INFO]: Starting minecraft server version 1.19.4
[14:32:11] [Server thread/INFO]: Loading properties
[14:32:11] [Server thread/INFO]: Default game type: SURVIVAL
[14:32:11] [Server thread/INFO]: Generating keypair
[14:32:11] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:32:11] [Server thread/INFO]: Using epoll channel type
[14:32:11] [Server thread/INFO]: Preparing level "world"
[14:32:11] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:14] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:15] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:32:15] [Server thread/INFO]: Time elapsed: 3827 ms
[14:32:15] [Server thread/INFO]: Done (3.936s)! For help, type "help"
[14:32:15] [Server thread/INFO]: Starting remote control listener
[14:32:15] [Server thread/INFO]: Thread RCON Listener started
[14:32:15] [Server thread/INFO]: RCON running on 0.0.0.0:25575
```

**Comment by intsuc** [comment]
Thanks for the report.

It seems that command injection has failed. I tried it under the same conditions except using OpenJDK 17.0.2, but I couldn't reproduce it.

Command injection depends on a specific class name (specifically `com/mojang/brigadier/CommandDispatcher`), so it may fail if you use a modded server. If you use a vanilla server, I can't think of any cause at this moment, and I need to do a more detailed investigation.

**Comment by a-happin** [comment]
Well..., I use a vanilla server.

**Comment by intsuc** [comment]
I've managed to reproduce it on Windows Subsystem for Linux. Seems to be a platform-specific issue. I've almost identified the cause and will release a fixed version soon.

**Comment by a-happin** [comment]
I was trying on docker on Linux, not WSL...is this a problem that happens in a virtual environment...?

**Comment by intsuc** [comment]
It seemed to be a formatting issue with the command-line arguments.
I believe 0.8.1 fixes this issue. If not, please reopen.

**Comment by a-happin** [comment]
It seems to be working now. Thank you very much! 💕
